# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

# Header
language: r
sudo: false
cache: packages
warnings_are_errors: false

#env
env:
  global:
  - _R_CHECK_FORCE_SUGGESTS_=false

after_success:
- Rscript -e 'covr::codecov()'

r_github_packages:
- jimhester/covr

#r_packages
r_packages:

#services
services:

#before_install
before_install:
